services:
  autofix_yii2_nginx:
    volumes:
      - "./docker/nginx/production/conf.d:/etc/nginx/conf.d"
      - "./docker/nginx/production/vhosts:/etc/nginx/vhosts"
      - "./docker/nginx/production/vhosts-includes:/etc/nginx/vhosts-includes"
      - "./docker/nginx/production/nginx.conf:/etc/nginx/nginx.conf"
      - ./src:/var/www/html
      - ./docker/certbot/www:/var/www/certbot:ro        # для проверки домена
      - ./docker/certbot/certs:/etc/letsencrypt:ro      # сертификаты
    ports:
      - "80:80"
      - "443:443"

  autofix_yii2_php:
    restart: always
#    build:
#      args:
#        - PHP_XDEBUG=no    # на сервере xdebug выключен
