services:
  # Nginx Web Server
  autofix_yii2_nginx:
    image: nginx:alpine
    container_name: autofix_yii2_nginx
    ports:
      - "80:80"
    depends_on:
      - autofix_yii2_php
      - autofix_yii2_db
    networks:
      - autofix_yii2_network
#    deploy:
#      resources:
#        limits:
#          memory: 64M

  # PHP-FPM
  autofix_yii2_php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - PHP_XDEBUG=$PHP_XDEBUG
    container_name: autofix_yii2_php
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=autofix_yii2_db
      - DB_PORT=3306
      - DB_DATABASE=autofix
      - DB_USERNAME=autofix_user
      - DB_PASSWORD=autofix_password
    depends_on:
      - autofix_yii2_db
    networks:
      - autofix_yii2_network
#    deploy:
#      resources:
#        limits:
#          memory: 256M

  # Database MariaDB next 11.8
  autofix_yii2_db:
    image: mariadb:11.8
    container_name: autofix_yii2_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: autofix
      MYSQL_USER: autofix_user
      MYSQL_PASSWORD: autofix_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb_memory.cnf:/etc/mysql/conf.d/my.cnf:ro  # подключаем конфиг
      - ./docker/db/logs:/var/log/mysql                  # логи на хост
    networks:
      - autofix_yii2_network
#    deploy:
#      resources:
#        limits:
#          memory: 512M

#  autofix_yii2_mailpit:
#    image: axllent/mailpit:latest
#    container_name: autofix_yii2_mailpit
#    restart: unless-stopped
#    ports:
#      - "1025:1025"   # SMTP порт для отправки
#      - "8025:8025"   # Web интерфейс
#    environment:
#      MP_SMTP_AUTH_ACCEPT_ANY: 1
#      MP_SMTP_AUTH_ALLOW_INSECURE: 1
#    volumes:
#      - mailpit-data:/data
#    networks:
#      - autofix_network

  # phpMyAdmin
  autofix_yii2_phpmyadmin:
    image: phpmyadmin:latest
    container_name: autofix_yii2_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: autofix_yii2_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - autofix_yii2_db
    networks:
      - autofix_yii2_network

networks:
  autofix_yii2_network:
    driver: bridge

volumes:
  db_data:
#  mailpit-data: