services:
  autofix_yii2_nginx:
    volumes:
      - "./docker/nginx/local/conf.d:/etc/nginx/conf.d"
      - "./docker/nginx/local/vhosts:/etc/nginx/vhosts"
      - "./docker/nginx/local/nginx.conf:/etc/nginx/nginx.conf"
      - ./src:/var/www/html
    ports:
      - "80:80"
#
#  autofix_yii2_php:
#    build:
#      args:
#        - PHP_XDEBUG=yes   # на локалке включаем xdebug