server {
    listen 443 ssl;
    server_name api.findmymechanic.ru;
    root /var/www/html/api/web;

    error_log  /var/log/nginx/https-api-error.log;
    access_log /var/log/nginx/https-api-access.log;

    include /etc/nginx/vhosts-includes/*.conf;
    index index.php index.html index.htm;

    ssl_certificate     /etc/letsencrypt/live/api.findmymechanic.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.findmymechanic.ru/privkey.pem;


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass autofix_yii2_php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ ^/assets/.*\.php$ {
        deny all;
    }


#     location ~ /\.(?!well-known).* {
#         deny all;
#     }

    client_max_body_size 100M;
}